language: ruby
rvm:
- 2.4.0
sudo: false
cache:
  bundler: true
  directories:
    - node_modules
  yarn: true
before_script:
- bin/rails db:create
- bin/rails db:migrate
install:
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn
script:
- bundle exec rspec
addons:
  postgresql: "9.4"